"""took out phone number for restaurant

Revision ID: 14c80d2ed292
Revises: 66adfac59f65
Create Date: 2021-12-15 20:44:55.353289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c80d2ed292'
down_revision = '66adfac59f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'phoneNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('phoneNumber', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
