"""took out everything after state on restaurants table

Revision ID: 6c315589aa1b
Revises: 8639f1bd34df
Create Date: 2021-12-16 16:33:40.736737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c315589aa1b'
down_revision = '8639f1bd34df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('restaurants_ownerId_fkey', 'restaurants', type_='foreignkey')
    op.drop_constraint('restaurants_categoryId_fkey', 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'created_at')
    op.drop_column('restaurants', 'imageUrl')
    op.drop_column('restaurants', 'review_count')
    op.drop_column('restaurants', 'ownerId')
    op.drop_column('restaurants', 'phoneNumber')
    op.drop_column('restaurants', 'updated_at')
    op.drop_column('restaurants', 'priceRating')
    op.drop_column('restaurants', 'stars')
    op.drop_column('restaurants', 'hours')
    op.drop_column('restaurants', 'zipcode')
    op.drop_column('restaurants', 'lat')
    op.drop_column('restaurants', 'categoryId')
    op.drop_column('restaurants', 'lng')
    op.drop_column('restaurants', 'websiteUrl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('websiteUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('lng', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('categoryId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('lat', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('zipcode', sa.NUMERIC(precision=5, scale=0), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('hours', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('priceRating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('phoneNumber', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('ownerId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('imageUrl', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key('restaurants_categoryId_fkey', 'restaurants', 'categories', ['categoryId'], ['id'])
    op.create_foreign_key('restaurants_ownerId_fkey', 'restaurants', 'users', ['ownerId'], ['id'])
    # ### end Alembic commands ###
