"""made edits to phone number data type in restaurants

Revision ID: 2b272a468fc1
Revises: 14c80d2ed292
Create Date: 2021-12-15 20:47:17.340443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b272a468fc1'
down_revision = '14c80d2ed292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('phoneNumber', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'phoneNumber')
    # ### end Alembic commands ###
