"""empty message

Revision ID: 3fa8124e2a59
Revises: 2b272a468fc1
Create Date: 2021-12-15 21:19:29.400245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fa8124e2a59'
down_revision = '2b272a468fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'websiteUrl')
    op.drop_column('restaurants', 'imageUrl')
    op.drop_column('restaurants', 'created_at')
    op.drop_column('restaurants', 'updated_at')
    op.drop_column('restaurants', 'phoneNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('phoneNumber', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('imageUrl', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('websiteUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
