"""empty message

Revision ID: 8639f1bd34df
Revises: 3fa8124e2a59
Create Date: 2021-12-15 21:20:04.039145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8639f1bd34df'
down_revision = '3fa8124e2a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('phoneNumber', sa.String(length=15), nullable=True))
    op.add_column('restaurants', sa.Column('websiteUrl', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('imageUrl', sa.String(), nullable=False))
    op.add_column('restaurants', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('restaurants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'updated_at')
    op.drop_column('restaurants', 'created_at')
    op.drop_column('restaurants', 'imageUrl')
    op.drop_column('restaurants', 'websiteUrl')
    op.drop_column('restaurants', 'phoneNumber')
    # ### end Alembic commands ###
